demo_home:
    path: /
    controller: App\Controller\DemoController::home
    methods: [GET]

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

