nowo_password_policy:
    entities:
        App\Entity\User:
            password_field: password
            password_history_field: passwordHistory
            passwords_to_remember: 5
            expiry_days: 90
            reset_password_route_name: demo_home
            notified_routes:
                - demo_home
            excluded_notified_routes: []

